/**
 * client/vite.config.js
 *
 * Vite configuration for NyayaSetu React PWA.
 * PWA via vite-plugin-pwa with Workbox runtime caching.
 */

import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { VitePWA } from 'vite-plugin-pwa';
import path from 'path';

export default defineConfig({
  plugins: [
    react(),

    VitePWA({
      // Register the service worker immediately and skip waiting
      registerType: 'autoUpdate',
      injectRegister: 'auto',

      // Path to manifest (already in public/)
      manifest: false, // We provide our own public/manifest.json

      // Dev mode — enable SW in development for testing
      devOptions: {
        enabled: process.env.NODE_ENV === 'development',
        type: 'module',
        navigateFallback: 'index.html',
      },

      // Workbox configuration
      workbox: {
        // Pre-cache all static assets generated by Vite
        globPatterns: ['**/*.{js,css,html,ico,png,svg,woff,woff2,ttf,eot}'],

        // Skip waiting so new SW takes over immediately
        skipWaiting: true,
        clientsClaim: true,

        // Navigation fallback for SPA
        navigateFallback: '/index.html',
        navigateFallbackDenylist: [
          // Don't apply fallback to API routes or webhook
          /^\/v1\//,
          /^\/api\//,
          /\/whatsapp\/webhook/,
        ],

        // Runtime caching strategies
        runtimeCaching: [
          // ── API calls — Network First ────────────────────────────────────
          // Always try network first so data is fresh; fall back to cache
          {
            urlPattern: /^https?:\/\/[^/]+\/v1\/.*/i,
            handler: 'NetworkFirst',
            options: {
              cacheName: 'nyayasetu-api-v1',
              networkTimeoutSeconds: 10,
              cacheableResponse: {
                statuses: [0, 200],
              },
              expiration: {
                maxEntries: 100,
                maxAgeSeconds: 60 * 5, // 5 minutes
              },
            },
          },

          // ── Static assets — Cache First ──────────────────────────────────
          // Images, fonts, icons served from /public
          {
            urlPattern: /\.(?:png|jpg|jpeg|svg|gif|webp|ico)$/i,
            handler: 'CacheFirst',
            options: {
              cacheName: 'nyayasetu-images',
              expiration: {
                maxEntries: 100,
                maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
              },
              cacheableResponse: { statuses: [0, 200] },
            },
          },

          // ── Google Fonts stylesheets — Stale While Revalidate ────────────
          {
            urlPattern: /^https:\/\/fonts\.googleapis\.com\/.*/i,
            handler: 'StaleWhileRevalidate',
            options: {
              cacheName: 'google-fonts-stylesheets',
              expiration: {
                maxEntries: 10,
                maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
              },
            },
          },

          // ── Google Fonts — Cache First ────────────────────────────────────
          {
            urlPattern: /^https:\/\/fonts\.gstatic\.com\/.*/i,
            handler: 'CacheFirst',
            options: {
              cacheName: 'google-fonts-webfonts',
              expiration: {
                maxEntries: 30,
                maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
              },
              cacheableResponse: { statuses: [0, 200] },
            },
          },

          // ── i18n locale files — Stale While Revalidate ───────────────────
          {
            urlPattern: /\/locales\/[a-z]+\/translation\.json$/i,
            handler: 'StaleWhileRevalidate',
            options: {
              cacheName: 'nyayasetu-i18n',
              expiration: {
                maxEntries: 20,
                maxAgeSeconds: 60 * 60 * 24, // 1 day
              },
              cacheableResponse: { statuses: [0, 200] },
            },
          },

          // ── Razorpay checkout script — Network First ─────────────────────
          {
            urlPattern: /^https:\/\/checkout\.razorpay\.com\/.*/i,
            handler: 'NetworkFirst',
            options: {
              cacheName: 'razorpay-checkout',
              networkTimeoutSeconds: 15,
              cacheableResponse: { statuses: [0, 200] },
            },
          },
        ],
      },
    }),
  ],

  resolve: {
    alias: {
      '@':       path.resolve(__dirname, './src'),
      '@shared': path.resolve(__dirname, '../shared'),
    },
  },

  server: {
    port: 3000,
    proxy: {
      '/v1': {
        target: process.env.VITE_API_TARGET || 'http://localhost:5000',
        changeOrigin: true,
        secure: false,
      },
    },
  },

  build: {
    outDir: 'dist',
    sourcemap: process.env.NODE_ENV === 'development',
    chunkSizeWarningLimit: 1000,
    rollupOptions: {
      output: {
        // Code splitting — split large vendor dependencies
        manualChunks: {
          react:    ['react', 'react-dom', 'react-router-dom'],
          mui:      ['@mui/material', '@mui/icons-material', '@emotion/react', '@emotion/styled'],
          framer:   ['framer-motion'],
          redux:    ['@reduxjs/toolkit', 'react-redux', 'redux-persist'],
          i18n:     ['i18next', 'react-i18next', 'i18next-http-backend', 'i18next-browser-languagedetector'],
          recharts: ['recharts'],
          forms:    ['react-hook-form', '@hookform/resolvers', 'yup'],
        },
      },
    },
  },

  // Optimise dependency pre-bundling
  optimizeDeps: {
    include: [
      'react',
      'react-dom',
      'react-router-dom',
      '@mui/material',
      'framer-motion',
      '@reduxjs/toolkit',
      'react-redux',
      'i18next',
      'react-i18next',
      'axios',
    ],
  },
});
