const PDFDocument = require('pdfkit');
const logger      = require('../../utils/logger');

// ─── Constants ─────────────────────────────────────────────────────────────────

const FONTS = {
  regular:    'Helvetica',
  bold:       'Helvetica-Bold',
  italic:     'Helvetica-Oblique',
  boldItalic: 'Helvetica-BoldOblique',
};

const COLORS = {
  primary:    '#1565C0',  // NyayaSetu brand blue
  dark:       '#0D1B2A',
  secondary:  '#455A64',
  divider:    '#CFD8DC',
  accent:     '#E3F2FD',
  disclaimer: '#78909C',
  citationBg: '#F8FAFF',
};

const MARGINS = { top: 60, bottom: 70, left: 70, right: 70 };

// ─── Helpers ───────────────────────────────────────────────────────────────────

function formatDate(date) {
  return new Date(date || Date.now()).toLocaleDateString('en-IN', {
    day: 'numeric', month: 'long', year: 'numeric',
  });
}

function sanitizeText(text) {
  if (!text) return '';
  // PDFKit handles Unicode but strip control chars that break layout
  return String(text).replace(/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/g, '');
}

/**
 * drawDivider — horizontal rule across the content area
 */
function drawDivider(doc, y, color = COLORS.divider) {
  const pageWidth = doc.page.width;
  doc.moveTo(MARGINS.left, y)
     .lineTo(pageWidth - MARGINS.right, y)
     .strokeColor(color)
     .lineWidth(0.5)
     .stroke();
}

/**
 * addPageNumbers — footer callback registered with each new page
 */
function addPageNumbers(doc) {
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    const pageNumber = i - range.start + 1;
    const totalPages = range.count;
    const pageW = doc.page.width;
    const pageH = doc.page.height;

    // Footer line
    drawDivider(doc, pageH - MARGINS.bottom + 10);

    doc.font(FONTS.regular)
       .fontSize(8)
       .fillColor(COLORS.disclaimer)
       .text(
         `Generated by NyayaSetu (nyayasetu.in) — For reference only, not a substitute for legal advice`,
         MARGINS.left,
         pageH - MARGINS.bottom + 16,
         { width: pageW - MARGINS.left - MARGINS.right - 60, align: 'left' }
       )
       .text(
         `Page ${pageNumber} of ${totalPages}`,
         pageW - MARGINS.right - 60,
         pageH - MARGINS.bottom + 16,
         { width: 60, align: 'right' }
       );
  }
}

// ─── Section renderers ─────────────────────────────────────────────────────────

/**
 * renderHeader — NyayaSetu logo text + document title + metadata bar
 */
function renderHeader(doc, document, user, template) {
  const pageW = doc.page.width;
  const contentW = pageW - MARGINS.left - MARGINS.right;

  // ── Logo bar ──────────────────────────────────────────────────────────────
  doc.rect(0, 0, pageW, 52)
     .fill(COLORS.primary);

  doc.font(FONTS.bold)
     .fontSize(20)
     .fillColor('#FFFFFF')
     .text('⚖ NyayaSetu', MARGINS.left, 16);

  doc.font(FONTS.regular)
     .fontSize(9)
     .fillColor('rgba(255,255,255,0.8)')
     .text('Bridge to Justice', MARGINS.left + 148, 20);

  // Document ref number (top right)
  const refNumber = `NS-${String(document._id).slice(-8).toUpperCase()}`;
  doc.font(FONTS.regular)
     .fontSize(8)
     .fillColor('rgba(255,255,255,0.7)')
     .text(`Ref: ${refNumber}`, pageW - MARGINS.right - 120, 20, { width: 120, align: 'right' });

  doc.y = 70;

  // ── Document title ────────────────────────────────────────────────────────
  doc.font(FONTS.bold)
     .fontSize(16)
     .fillColor(COLORS.dark)
     .text(sanitizeText(document.title || template.name), MARGINS.left, doc.y, {
       width: contentW, align: 'center',
     });

  doc.moveDown(0.4);
  drawDivider(doc, doc.y);
  doc.moveDown(0.6);

  // ── Metadata strip ────────────────────────────────────────────────────────
  const metaY = doc.y;
  const colW  = contentW / 3;

  const metaItems = [
    { label: 'Generated by', value: user?.name || 'NyayaSetu User' },
    { label: 'Date',         value: formatDate(document.createdAt) },
    { label: 'Jurisdiction', value: document.jurisdiction?.state || 'India' },
  ];

  metaItems.forEach((item, i) => {
    const x = MARGINS.left + i * colW;
    doc.font(FONTS.regular)
       .fontSize(8)
       .fillColor(COLORS.secondary)
       .text(item.label.toUpperCase(), x, metaY, { width: colW - 10 });
    doc.font(FONTS.bold)
       .fontSize(9)
       .fillColor(COLORS.dark)
       .text(sanitizeText(item.value), x, metaY + 12, { width: colW - 10 });
  });

  doc.y = metaY + 32;
  drawDivider(doc, doc.y);
  doc.moveDown(1);
}

/**
 * renderDocumentBody — the core legal text, split into paragraphs
 */
function renderDocumentBody(doc, document) {
  const pageW    = doc.page.width;
  const contentW = pageW - MARGINS.left - MARGINS.right;
  const text     = sanitizeText(document.content || document.documentText || '');

  if (!text) return;

  const paragraphs = text.split(/\n{2,}|\r\n\r\n/).filter((p) => p.trim());

  for (const para of paragraphs) {
    const trimmed = para.trim();
    if (!trimmed) continue;

    // ── Detect paragraph type and style accordingly ────────────────────────
    const isAllCaps   = trimmed === trimmed.toUpperCase() && trimmed.length < 80 && /[A-Z]{3}/.test(trimmed);
    const isNumbered  = /^(\d+\.|[ivxIVX]+\.)/.test(trimmed);
    const isSalutation = /^(To,|From,|Sub:|Subject:|Respected|Dear|The\s+(Honourable|Hon'ble))/i.test(trimmed);
    const isSignature  = /^(Yours faithfully|Yours sincerely|Thanking you|Respectfully|Complainant|Petitioner|Applicant)/i.test(trimmed);
    const isDate       = /^(Date:|Place:|Dated:|On this)/i.test(trimmed);

    // Ensure we don't overflow into the footer zone
    const remainingY = doc.page.height - MARGINS.bottom - doc.y;
    if (remainingY < 60) doc.addPage();

    if (isAllCaps && !isNumbered) {
      // Section heading
      doc.moveDown(0.5);
      doc.font(FONTS.bold)
         .fontSize(11)
         .fillColor(COLORS.primary)
         .text(sanitizeText(trimmed), MARGINS.left, doc.y, { width: contentW });
      doc.moveDown(0.4);
      drawDivider(doc, doc.y, COLORS.accent);
      doc.moveDown(0.4);
    } else if (isSalutation) {
      doc.font(FONTS.regular)
         .fontSize(10)
         .fillColor(COLORS.dark)
         .text(sanitizeText(trimmed), MARGINS.left, doc.y, { width: contentW });
      doc.moveDown(0.6);
    } else if (isSignature || isDate) {
      doc.moveDown(0.3);
      doc.font(FONTS.regular)
         .fontSize(10)
         .fillColor(COLORS.dark)
         .text(sanitizeText(trimmed), MARGINS.left, doc.y, { width: contentW });
      doc.moveDown(0.4);
    } else if (isNumbered) {
      doc.font(FONTS.regular)
         .fontSize(10)
         .fillColor(COLORS.dark)
         .text(sanitizeText(trimmed), MARGINS.left + 16, doc.y, {
           width: contentW - 16,
           indent: -16,
         });
      doc.moveDown(0.5);
    } else {
      // Normal paragraph
      doc.font(FONTS.regular)
         .fontSize(10)
         .fillColor(COLORS.dark)
         .text(sanitizeText(trimmed), MARGINS.left, doc.y, {
           width: contentW,
           align: 'justify',
           lineGap: 2,
         });
      doc.moveDown(0.7);
    }
  }
}

/**
 * renderNextSteps — numbered action guide for the user
 */
function renderNextSteps(doc, nextSteps) {
  if (!nextSteps || nextSteps.length === 0) return;

  const pageW    = doc.page.width;
  const contentW = pageW - MARGINS.left - MARGINS.right;

  doc.addPage();

  // Section header
  doc.rect(MARGINS.left, doc.y, contentW, 28)
     .fill(COLORS.primary);
  doc.font(FONTS.bold)
     .fontSize(12)
     .fillColor('#FFFFFF')
     .text('NEXT STEPS — WHAT YOU SHOULD DO NOW', MARGINS.left + 12, doc.y + 8, { width: contentW - 24 });
  doc.y += 36;
  doc.moveDown(0.5);

  nextSteps.forEach((step, i) => {
    const remainingY = doc.page.height - MARGINS.bottom - doc.y;
    if (remainingY < 80) doc.addPage();

    const stepY = doc.y;

    // Step number circle
    doc.circle(MARGINS.left + 14, stepY + 12, 12)
       .fill(COLORS.primary);
    doc.font(FONTS.bold)
       .fontSize(10)
       .fillColor('#FFFFFF')
       .text(String(step.step || i + 1), MARGINS.left + 8, stepY + 7, { width: 12, align: 'center' });

    // Step content
    const stepX = MARGINS.left + 34;
    const stepW = contentW - 34;

    doc.font(FONTS.bold)
       .fontSize(10)
       .fillColor(COLORS.dark)
       .text(sanitizeText(step.instruction || ''), stepX, stepY, { width: stepW });

    doc.y += 2;

    const metaLine = [
      step.authority ? `📍 ${step.authority}` : null,
      step.fee       ? `💰 Fee: ${step.fee}` : null,
      step.timelineExpected ? `⏱ ${step.timelineExpected}` : null,
    ].filter(Boolean).join('   ');

    if (metaLine) {
      doc.font(FONTS.regular)
         .fontSize(8.5)
         .fillColor(COLORS.secondary)
         .text(sanitizeText(metaLine), stepX, doc.y, { width: stepW });
    }

    if (step.onlineLink) {
      doc.moveDown(0.2);
      doc.font(FONTS.italic)
         .fontSize(8)
         .fillColor(COLORS.primary)
         .text(`🔗 ${step.onlineLink}`, stepX, doc.y, { width: stepW, link: step.onlineLink });
    }

    doc.moveDown(0.8);

    // Light separator between steps
    if (i < nextSteps.length - 1) {
      drawDivider(doc, doc.y, '#EEF2FF');
      doc.moveDown(0.5);
    }
  });
}

/**
 * renderLegalCitations — footnote-style citation table
 */
function renderLegalCitations(doc, legalCitations) {
  if (!legalCitations || legalCitations.length === 0) return;

  const pageW    = doc.page.width;
  const contentW = pageW - MARGINS.left - MARGINS.right;

  const remainingY = doc.page.height - MARGINS.bottom - doc.y;
  if (remainingY < 120) doc.addPage();

  doc.moveDown(1);

  // Section header
  doc.font(FONTS.bold)
     .fontSize(11)
     .fillColor(COLORS.primary)
     .text('LEGAL CITATIONS', MARGINS.left, doc.y, { width: contentW });
  doc.moveDown(0.3);
  drawDivider(doc, doc.y, COLORS.primary);
  doc.moveDown(0.6);

  legalCitations.forEach((cite, i) => {
    const remainingY = doc.page.height - MARGINS.bottom - doc.y;
    if (remainingY < 60) doc.addPage();

    // Background box
    const boxH = 44;
    doc.rect(MARGINS.left, doc.y, contentW, boxH)
       .fill(COLORS.citationBg);
    doc.rect(MARGINS.left, doc.y, 4, boxH)
       .fill(COLORS.primary);

    const citeY = doc.y + 6;
    const citeX = MARGINS.left + 12;
    const citeW = contentW - 16;

    doc.font(FONTS.bold)
       .fontSize(9)
       .fillColor(COLORS.dark)
       .text(
         `[${i + 1}] ${sanitizeText(cite.act)}${cite.section ? ` — ${sanitizeText(cite.section)}` : ''}`,
         citeX, citeY, { width: citeW }
       );

    doc.font(FONTS.regular)
       .fontSize(8)
       .fillColor(COLORS.secondary)
       .text(sanitizeText(cite.description || ''), citeX, citeY + 14, { width: citeW - 100 });

    if (cite.url) {
      doc.font(FONTS.italic)
         .fontSize(7.5)
         .fillColor(COLORS.primary)
         .text('View on Indian Kanoon →', citeX + citeW - 120, citeY + 14, {
           width: 120, align: 'right', link: cite.url,
         });
    }

    doc.y += boxH + 5;
  });
}

// ─── Main export ───────────────────────────────────────────────────────────────

/**
 * generateLegalDocument — produces a complete, print-ready PDF buffer.
 *
 * @param {object} document  — Document model instance (has content, legalCitations, nextSteps)
 * @param {object} user      — User model instance (name, state)
 * @param {object} template  — DocumentTemplate model instance
 * @returns {Promise<Buffer>}
 */
async function generateLegalDocument(document, user, template) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size:          'A4',
        margins:       MARGINS,
        bufferPages:   true, // Required for addPageNumbers post-processing
        info: {
          Title:    document.title || template.name,
          Author:   'NyayaSetu',
          Subject:  template.name,
          Creator:  'NyayaSetu Legal Platform (nyayasetu.in)',
          Keywords: `legal, india, ${template.category}, ${document.jurisdiction?.state || 'india'}`,
        },
      });

      const chunks = [];
      doc.on('data',  (chunk) => chunks.push(chunk));
      doc.on('error', reject);
      doc.on('end', () => {
        const buffer = Buffer.concat(chunks);
        logger.info(`[pdfGenerator] Generated PDF: ${buffer.length} bytes, doc: ${document._id}`);
        resolve(buffer);
      });

      // ── Page 1: Header + body ─────────────────────────────────────────────
      renderHeader(doc, document, user, template);
      renderDocumentBody(doc, document);

      // ── Next Steps page ───────────────────────────────────────────────────
      if (document.nextSteps && document.nextSteps.length > 0) {
        renderNextSteps(doc, document.nextSteps);
      }

      // ── Legal Citations (final section) ───────────────────────────────────
      if (document.legalCitations && document.legalCitations.length > 0) {
        renderLegalCitations(doc, document.legalCitations);
      }

      // ── Watermark: DRAFT for unpaid free-tier docs ─────────────────────────
      if (!document.isPaid && document.accessType === 'free_tier') {
        const range = doc.bufferedPageRange();
        for (let i = range.start; i < range.start + range.count; i++) {
          doc.switchToPage(i);
          doc.save();
          doc.rotate(45, { origin: [doc.page.width / 2, doc.page.height / 2] });
          doc.font(FONTS.bold)
             .fontSize(72)
             .fillColor('#E3E8F0')
             .opacity(0.3)
             .text('PREVIEW', 100, doc.page.height / 2 - 40, {
               width: doc.page.width - 200, align: 'center',
             });
          doc.restore();
        }
      }

      // ── Page numbers (must be last) ───────────────────────────────────────
      addPageNumbers(doc);

      doc.flushPages();
      doc.end();
    } catch (err) {
      logger.error('[pdfGenerator] Failed:', { error: err.message });
      reject(err);
    }
  });
}

module.exports = { generateLegalDocument };
