const logger = require('../../utils/logger');

// ─── Provider: Nodemailer/Gmail ────────────────────────────────────────────────

async function sendViaGmail(to, subject, html, text) {
  const nodemailer = require('nodemailer');

  const transporter = nodemailer.createTransporter({
    host:   process.env.EMAIL_HOST  || 'smtp.gmail.com',
    port:   parseInt(process.env.EMAIL_PORT || '587'),
    secure: process.env.EMAIL_PORT === '465',
    auth: {
      user: process.env.EMAIL_USER,
      pass: process.env.EMAIL_PASS,
    },
  });

  const info = await transporter.sendMail({
    from:    process.env.EMAIL_FROM || '"NyayaSetu" <noreply@nyayasetu.in>',
    to,
    subject,
    html,
    text,
  });

  logger.info(`[email/gmail] Sent to ${to}: ${info.messageId}`);
  return { provider: 'gmail', messageId: info.messageId };
}

// ─── Provider: SendGrid ────────────────────────────────────────────────────────

async function sendViaSendGrid(to, subject, html, text) {
  const sgMail = require('@sendgrid/mail');
  sgMail.setApiKey(process.env.SENDGRID_API_KEY);

  const [response] = await sgMail.send({
    to,
    from:    process.env.EMAIL_FROM || 'noreply@nyayasetu.in',
    subject,
    html,
    text,
  });

  logger.info(`[email/sendgrid] Sent to ${to}, status: ${response.statusCode}`);
  return { provider: 'sendgrid', statusCode: response.statusCode };
}

// ─── HTML template builder ────────────────────────────────────────────────────

function buildHearingAlertHtml({ caseTitle, hearingDate, court, cnrNumber, documentUrl }) {
  const dateStr = hearingDate
    ? new Date(hearingDate).toLocaleDateString('en-IN', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })
    : 'Date to be confirmed';

  return `
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Hearing Reminder — NyayaSetu</title></head>
<body style="margin:0;padding:0;font-family:'DM Sans',Arial,sans-serif;background:#F8FAFF;">
  <table width="100%" cellpadding="0" cellspacing="0" border="0">
    <tr><td align="center" style="padding:32px 16px;">
      <table width="600" cellpadding="0" cellspacing="0" border="0" style="background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 4px 12px rgba(0,0,0,0.08);">
        <!-- Header -->
        <tr><td style="background:#1565C0;padding:24px 32px;">
          <h1 style="margin:0;color:#fff;font-size:20px;">⚖ NyayaSetu</h1>
          <p style="margin:4px 0 0;color:rgba(255,255,255,0.8);font-size:13px;">Bridge to Justice</p>
        </td></tr>
        <!-- Body -->
        <tr><td style="padding:32px;">
          <h2 style="margin:0 0 8px;color:#0D1B2A;font-size:22px;">🏛️ Upcoming Hearing Reminder</h2>
          <p style="color:#455A64;margin:0 0 24px;">This is a reminder about your upcoming court hearing.</p>
          <!-- Case details box -->
          <table width="100%" cellpadding="0" cellspacing="0" style="background:#F8FAFF;border:1px solid #CFD8DC;border-radius:8px;margin-bottom:24px;">
            <tr><td style="padding:20px;">
              <p style="margin:0 0 12px;font-size:16px;font-weight:bold;color:#0D1B2A;">${caseTitle || 'Your Case'}</p>
              <p style="margin:0 0 8px;color:#455A64;font-size:14px;">📅 <strong>Date:</strong> ${dateStr}</p>
              <p style="margin:0 0 8px;color:#455A64;font-size:14px;">🏛️ <strong>Court:</strong> ${court || 'As per notice'}</p>
              ${cnrNumber ? `<p style="margin:0;color:#455A64;font-size:14px;font-family:monospace;">🔖 <strong>CNR:</strong> ${cnrNumber}</p>` : ''}
            </td></tr>
          </table>
          <p style="color:#455A64;font-size:14px;margin:0 0 24px;">Please ensure all required documents are ready and arrive on time.</p>
          ${documentUrl ? `<a href="${documentUrl}" style="display:inline-block;background:#1565C0;color:#fff;padding:12px 24px;border-radius:8px;text-decoration:none;font-weight:bold;font-size:14px;">View Your Documents →</a>` : ''}
        </td></tr>
        <!-- Footer -->
        <tr><td style="background:#F8FAFF;padding:20px 32px;border-top:1px solid #E3E8F0;">
          <p style="margin:0;color:#78909C;font-size:12px;">Generated by NyayaSetu — nyayasetu.in | This is an automated reminder.</p>
          <p style="margin:4px 0 0;color:#78909C;font-size:11px;">To stop hearing alerts, update your settings at nyayasetu.in/settings</p>
        </td></tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`;
}

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * sendEmail — dispatch an email via the configured provider.
 *
 * EMAIL_PROVIDER: 'gmail' (dev) | 'sendgrid' (prod)
 */
async function sendEmail({ to, subject, html, text }) {
  const provider = process.env.EMAIL_PROVIDER || 'gmail';

  try {
    switch (provider) {
      case 'sendgrid': return await sendViaSendGrid(to, subject, html, text);
      case 'gmail':
      default:         return await sendViaGmail(to, subject, html, text);
    }
  } catch (err) {
    logger.error(`[emailService] Failed to send to ${to}: ${err.message}`);
    throw err;
  }
}

/**
 * sendHearingAlertEmail — convenience wrapper for the standard hearing alert template.
 */
async function sendHearingAlertEmail({ to, caseTitle, hearingDate, court, cnrNumber, documentUrl }) {
  const dateStr = hearingDate
    ? new Date(hearingDate).toLocaleDateString('en-IN', { month: 'long', day: 'numeric', year: 'numeric' })
    : 'Date TBC';

  const subject = `🏛️ Court Hearing Reminder: ${caseTitle || 'Your Case'} — ${dateStr}`;
  const html    = buildHearingAlertHtml({ caseTitle, hearingDate, court, cnrNumber, documentUrl });
  const text    = `Hearing Reminder\n\nCase: ${caseTitle}\nDate: ${dateStr}\nCourt: ${court || 'As per notice'}\n\nNyayaSetu — nyayasetu.in`;

  return sendEmail({ to, subject, html, text });
}

module.exports = { sendEmail, sendHearingAlertEmail };
